# Generated by Django 5.1.3 on 2025-03-20 19:53

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('tags', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Measurement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('description', models.TextField(blank=True)),
            ],
        ),
        migrations.CreateModel(
            name='MutantType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('definition', models.TextField(blank=True)),
            ],
        ),
        migrations.CreateModel(
            name='Observable',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('description', models.TextField(blank=True, null=True)),
                ('modified_on', models.DateField(auto_now=True, null=True)),
                ('tags', models.ManyToManyField(blank=True, related_name='observables', to='tags.tag')),
            ],
            options={
                'get_latest_by': 'modified_on',
            },
        ),
        migrations.CreateModel(
            name='Phenotype',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('description', models.TextField(blank=True, null=True)),
                ('reporter', models.CharField(blank=True, max_length=200, null=True)),
                ('modified_on', models.DateField(auto_now=True, null=True)),
                ('measurement', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='phenotypes.measurement')),
                ('observable', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='phenotypes.observable')),
                ('tags', models.ManyToManyField(blank=True, related_name='phenotypes', to='tags.tag')),
            ],
        ),
    ]
