# Generated by Django 3.0.8 on 2020-08-12 16:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("phenotypes", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="phenotype",
            name="observable2",
        ),
    ]
