# Generated by Django 3.0.8 on 2020-08-12 17:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("phenotypes", "0002_remove_phenotype_observable2"),
    ]

    operations = [
        migrations.DeleteModel(
            name="Observable2",
        ),
    ]
