# Generated by Django 3.0.8 on 2020-07-21 18:18

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Paper",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("first_author", models.CharField(max_length=200)),
                (
                    "last_author",
                    models.CharField(blank=True, max_length=200, null=True),
                ),
                ("pub_date", models.IntegerField(default=0)),
                ("pmid", models.IntegerField(default=0)),
                ("notes", models.TextField(blank=True)),
                ("private_notes", models.TextField(blank=True)),
                ("data_abstract", models.TextField(blank=True, null=True)),
                ("modified_on", models.DateField(auto_now=True)),
            ],
            options={
                "ordering": ["pmid", "first_author", "last_author"],
                "get_latest_by": "modified_on",
            },
        ),
        migrations.CreateModel(
            name="Status",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        blank=True, default="undefined", max_length=200, null=True
                    ),
                ),
                ("description", models.TextField(blank=True, null=True)),
                ("is_valid", models.BooleanField()),
            ],
            options={
                "ordering": ["name"],
            },
        ),
        migrations.CreateModel(
            name="Statustested",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("status_date", models.DateField()),
                (
                    "paper",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        to="papers.Paper",
                    ),
                ),
                (
                    "status",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        to="papers.Status",
                    ),
                ),
            ],
            options={
                "get_latest_by": "id",
            },
        ),
        migrations.CreateModel(
            name="Statusdata",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("status_date", models.DateField()),
                (
                    "paper",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        to="papers.Paper",
                    ),
                ),
                (
                    "status",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        to="papers.Status",
                    ),
                ),
            ],
            options={
                "get_latest_by": "id",
            },
        ),
        migrations.AddField(
            model_name="paper",
            name="data_statuses",
            field=models.ManyToManyField(
                related_name="data_statuses",
                through="papers.Statusdata",
                to="papers.Status",
            ),
        ),
        migrations.AddField(
            model_name="paper",
            name="latest_data_status",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="latest_data_status_of_paper",
                to="papers.Statusdata",
            ),
        ),
        migrations.AddField(
            model_name="paper",
            name="latest_tested_status",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="latest_tested_status_of_paper",
                to="papers.Statustested",
            ),
        ),
        migrations.AddField(
            model_name="paper",
            name="tested_statuses",
            field=models.ManyToManyField(
                related_name="tested_statuses",
                through="papers.Statustested",
                to="papers.Status",
            ),
        ),
        migrations.AddField(
            model_name="paper",
            name="user",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.DO_NOTHING,
                to=settings.AUTH_USER_MODEL,
            ),
        ),
    ]
