# Generated by Django 5.1.3 on 2025-03-20 19:53

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('tags', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Status',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, default='undefined', max_length=200, null=True)),
                ('description', models.TextField(blank=True, null=True)),
                ('is_valid', models.BooleanField()),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Paper',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pmid', models.IntegerField(default=0, unique=True)),
                ('first_author', models.CharField(max_length=200)),
                ('last_author', models.CharField(blank=True, max_length=200, null=True)),
                ('pub_date', models.IntegerField(default=0)),
                ('systematic_name', models.CharField(max_length=200)),
                ('notes', models.TextField(blank=True, null=True)),
                ('private_notes', models.TextField(blank=True)),
                ('data_abstract', models.TextField(blank=True, null=True)),
                ('observables_summary', models.TextField(blank=True, null=True)),
                ('conditiontypes_summary', models.TextField(blank=True, null=True)),
                ('modified_on', models.DateField(auto_now=True)),
                ('tags', models.ManyToManyField(blank=True, to='tags.tag')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['pmid', 'systematic_name'],
                'get_latest_by': 'modified_on',
            },
        ),
        migrations.CreateModel(
            name='Statusdata',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status_date', models.DateField()),
                ('paper', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='papers.paper')),
                ('status', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='papers.status')),
            ],
            options={
                'get_latest_by': 'id',
            },
        ),
        migrations.AddField(
            model_name='paper',
            name='data_statuses',
            field=models.ManyToManyField(related_name='data_statuses', through='papers.Statusdata', to='papers.status'),
        ),
        migrations.AddField(
            model_name='paper',
            name='latest_data_status',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='latest_data_status_of_paper', to='papers.statusdata'),
        ),
        migrations.CreateModel(
            name='Statustested',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status_date', models.DateField()),
                ('paper', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='papers.paper')),
                ('status', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='papers.status')),
            ],
            options={
                'get_latest_by': 'id',
            },
        ),
        migrations.AddField(
            model_name='paper',
            name='latest_tested_status',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='latest_tested_status_of_paper', to='papers.statustested'),
        ),
        migrations.AddField(
            model_name='paper',
            name='tested_statuses',
            field=models.ManyToManyField(related_name='tested_statuses', through='papers.Statustested', to='papers.status'),
        ),
    ]
