# Generated by Django 5.1.3 on 2025-04-03 00:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('papers', '0002_paper_abstract_paper_citation_paper_title'),
    ]

    operations = [
        migrations.AddField(
            model_name='paper',
            name='authors',
            field=models.TextField(blank=True, null=True),
        ),
    ]
