# Generated by Django 5.1.3 on 2025-04-05 14:37

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('papers', '0003_paper_authors'),
    ]

    operations = [
        migrations.AlterField(
            model_name='statusdata',
            name='paper',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='papers.paper'),
        ),
        migrations.AlterField(
            model_name='statustested',
            name='paper',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='papers.paper'),
        ),
    ]
