# Generated by Django 3.0.8 on 2020-07-21 18:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Condition",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("dose", models.CharField(max_length=200)),
                ("description", models.TextField(blank=True, null=True)),
                ("modified_on", models.DateField(auto_now=True, null=True)),
            ],
            options={
                "get_latest_by": "modified_on",
            },
        ),
        migrations.CreateModel(
            name="Tag",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=200)),
                (
                    "description",
                    models.TextField(blank=True, max_length=1000, null=True),
                ),
                ("order", models.IntegerField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name="Medium",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "systematic_name",
                    models.CharField(blank=True, max_length=1000, null=True),
                ),
                (
                    "common_name",
                    models.CharField(blank=True, max_length=200, null=True),
                ),
                (
                    "display_name",
                    models.CharField(blank=True, max_length=1000, null=True),
                ),
                ("description", models.TextField(blank=True, null=True)),
                (
                    "conditions",
                    models.ManyToManyField(blank=True, to="conditions.Condition"),
                ),
            ],
        ),
        migrations.CreateModel(
            name="ConditionType",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=200)),
                ("other_names", models.TextField(blank=True, null=True)),
                (
                    "pubchem_id",
                    models.PositiveIntegerField(blank=True, null=True, unique=True),
                ),
                (
                    "pubchem_name",
                    models.CharField(blank=True, max_length=200, null=True),
                ),
                (
                    "chebi_id",
                    models.PositiveIntegerField(blank=True, null=True, unique=True),
                ),
                ("chebi_name", models.CharField(blank=True, max_length=200, null=True)),
                ("description", models.TextField(blank=True, null=True)),
                ("tags", models.ManyToManyField(blank=True, to="conditions.Tag")),
            ],
            options={
                "ordering": ["chebi_name", "pubchem_name", "name", "other_names"],
            },
        ),
        migrations.CreateModel(
            name="ConditionSet",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "systematic_name",
                    models.CharField(blank=True, max_length=1000, null=True),
                ),
                (
                    "common_name",
                    models.CharField(blank=True, max_length=200, null=True),
                ),
                (
                    "display_name",
                    models.CharField(blank=True, max_length=1000, null=True),
                ),
                ("description", models.TextField(blank=True, null=True)),
                (
                    "conditions",
                    models.ManyToManyField(blank=True, to="conditions.Condition"),
                ),
            ],
        ),
        migrations.AddField(
            model_name="condition",
            name="type",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.DO_NOTHING,
                to="conditions.ConditionType",
            ),
        ),
    ]
