# Generated by Django 5.1.3 on 2025-03-20 19:53

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('tags', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Condition',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dose', models.CharField(max_length=200)),
                ('description', models.TextField(blank=True, null=True)),
                ('modified_on', models.DateField(auto_now=True, null=True)),
                ('tags', models.ManyToManyField(blank=True, to='tags.tag')),
            ],
            options={
                'get_latest_by': 'modified_on',
            },
        ),
        migrations.CreateModel(
            name='ConditionSet',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('systematic_name', models.CharField(blank=True, max_length=1000, null=True)),
                ('common_name', models.CharField(blank=True, max_length=200, null=True)),
                ('display_name', models.CharField(blank=True, max_length=1000, null=True)),
                ('description', models.TextField(blank=True, null=True)),
                ('conditions', models.ManyToManyField(blank=True, to='conditions.condition')),
                ('tags', models.ManyToManyField(blank=True, to='tags.tag')),
            ],
        ),
        migrations.CreateModel(
            name='ConditionType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='Common name for display')),
                ('other_names', models.TextField(blank=True, null=True)),
                ('pubchem_id', models.PositiveIntegerField(blank=True, null=True, unique=True)),
                ('pubchem_name', models.CharField(blank=True, max_length=200, null=True)),
                ('chebi_id', models.PositiveIntegerField(blank=True, null=True, unique=True)),
                ('chebi_name', models.CharField(blank=True, max_length=200, null=True)),
                ('description', models.TextField(blank=True, null=True)),
                ('tags', models.ManyToManyField(blank=True, to='tags.tag')),
            ],
            options={
                'ordering': ['name', 'chebi_name', 'pubchem_name', 'other_names'],
            },
        ),
        migrations.AddField(
            model_name='condition',
            name='type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='conditions', to='conditions.conditiontype'),
        ),
        migrations.CreateModel(
            name='Medium',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('systematic_name', models.CharField(blank=True, max_length=1000, null=True)),
                ('common_name', models.CharField(blank=True, max_length=200, null=True)),
                ('display_name', models.CharField(blank=True, max_length=1000, null=True)),
                ('description', models.TextField(blank=True, null=True)),
                ('conditions', models.ManyToManyField(blank=True, to='conditions.condition')),
                ('tags', models.ManyToManyField(blank=True, to='tags.tag')),
            ],
        ),
    ]
