# Generated by Django 3.0.8 on 2020-10-24 19:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("conditions", "0001_initial"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="conditiontype",
            options={"ordering": ["name", "chebi_name", "pubchem_name", "other_names"]},
        ),
        migrations.AddField(
            model_name="condition",
            name="tags",
            field=models.ManyToManyField(blank=True, to="conditions.Tag"),
        ),
        migrations.AlterField(
            model_name="conditiontype",
            name="name",
            field=models.CharField(
                max_length=200, verbose_name="common name for display"
            ),
        ),
    ]
