# Generated by Django 5.1.3 on 2025-07-11 22:48

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='GeneAlias',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=250, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Gene',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('systematic_name', models.CharField(blank=True, max_length=50, null=True, unique=True)),
                ('primary_sgdid', models.CharField(blank=True, max_length=50, null=True)),
                ('common_name', models.CharField(blank=True, max_length=50, null=True)),
                ('common_name_explanation', models.CharField(blank=True, max_length=255, null=True)),
                ('description', models.TextField(blank=True, null=True)),
                ('puddu', models.CharField(blank=True, max_length=50, null=True)),
                ('qc_comments', models.TextField(blank=True, null=True)),
                ('aliases', models.ManyToManyField(blank=True, to='genes.genealias')),
            ],
        ),
    ]
