# Generated by Django 3.0.8 on 2020-09-04 23:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("datasets", "0005_auto_20200903_2004"),
    ]

    operations = [
        migrations.AddField(
            model_name="datasetsimilarity",
            name="pvalue",
            field=models.DecimalField(decimal_places=6, default=None, max_digits=10),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="genesimilarity",
            name="pvalue",
            field=models.DecimalField(decimal_places=6, default=None, max_digits=10),
            preserve_default=False,
        ),
    ]
