# Generated by Django 3.0.8 on 2020-09-12 17:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("datasets", "0006_auto_20200904_2323"),
    ]

    operations = [
        migrations.CreateModel(
            name="GeneAlias",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name",
                    models.CharField(blank=True, max_length=50, null=True, unique=True),
                ),
            ],
        ),
        migrations.AddField(
            model_name="gene",
            name="primary_sgdid",
            field=models.CharField(blank=True, max_length=50, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name="gene",
            name="common_name",
            field=models.CharField(blank=True, max_length=50, null=True, unique=True),
        ),
        migrations.AddField(
            model_name="gene",
            name="aliases",
            field=models.ManyToManyField(blank=True, to="datasets.GeneAlias"),
        ),
    ]
