# Generated by Django 3.0.8 on 2020-09-12 18:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("datasets", "0007_auto_20200912_1726"),
    ]

    operations = [
        migrations.AlterField(
            model_name="genealias",
            name="name",
            field=models.CharField(blank=True, max_length=250, null=True, unique=True),
        ),
    ]
